include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-podkop-sub
PKG_VERSION:=0.2.0
PKG_RELEASE:=1

PKG_LICENSE:=MIT
PKG_MAINTAINER:=wigarddev

LUCI_TITLE:=LuCI support for podkop-sub
LUCI_DEPENDS:=+podkop-sub
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
